# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d23cc14890904b3b7a4c1715d7582686c105bd99b1a823acf9b829a892d81b4b1de85e403007eaeef365f405a3fb6edbe07d7a8f52fb56f1055818bcd81954
  mailgun_api_key: key-0ff3314990fe930634141b11af0835b8
  mailgun_domain: sandbox5d17226037754d60b141ae617eef45d6.mailgun.org
  s3_bucket: dev.trd.st
  aws_access_key_id: AKIAI7B764VLZOY4JRJA
  aws_secret_access_key: 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
  facebook_app_id: 1762194004056248

test:
  secret_key_base: b78940ca09585c9d7ff430d5596bdc7e387fe4bfb72d9e27647def827f6d88e4b72bbe776b89ef991207c3211e99ad17a3abc1769d78cf0825920ddac47fffbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailgun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
  mailer_default_url: trd.st
  s3_bucket: trd.st
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
